### PR TITLE
Feature: Modificar os conceitos de avaliação

### PR DESCRIPTION
**Pull request by jvsn**
Feature: Modificar os conceitos de avaliação do projeto (ex: por default o projeto é setado como MA, MPA, e MANA. Minha feature é para modificar esses conceitos para, por exemplo, Aprovado e Reprovado).

---
This change is [Reviewable](https://reviewable.io/reviews/pauloborba/ta/38)

### CODE REVIEW

**Comment by Arthurlpgc** [comment]
Reviewed 26 of 27 files at r1.
Review status: 26 of 27 files reviewed at latest revision, 8 unresolved discussions.

---

_[grails-app/domain/ta/EvaluationConcept.groovy, line 5 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5VO7dhlSMRrUDx740:-KW5VO7dhlSMRrUDx741:b30dvsb) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/grails-app/domain/ta/EvaluationConcept.groovy#L5)):_

> ``` Groovy
> class EvaluationConcept {
>     String nome;
>     static hasMany = [conceitos: Concept]
> ```

Ja que o codigo ta todo em ingles, o uso de duas linguas difilcuta o entendimento do codigo

---

_[test/functional/pages/ConceptPages/AddConceptPage.groovy, line 12 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5WyrRixonZiUECexh:-KW5WyrSmizBmmErVN7e:b9zxubs) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/pages/ConceptPages/AddConceptPage.groovy#L12)):_

> ``` Groovy
> 
>     static at = {
> //        title ==~ /Criar Concept/
> ```

Comentario desnecessario

---

_[test/functional/pages/ConceptPages/EditConceptPage.groovy, line 13 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5X6cx6uZ8_aGZl8Hu:-KW5X6cx6uZ8_aGZl8Hv:b-1f0foh) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/pages/ConceptPages/EditConceptPage.groovy#L13)):_

> ``` Groovy
>     static at = {
>         title ==~ /Edit Concept/
> //        title ==~ /Editar Concept/
> ```

De novo, comentario de tradução de titulo

---

_[test/functional/pages/ConceptPages/ShowConceptPage.groovy, line 13 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5XBFYYx9C91kfJ8DP:-KW5XBFYYx9C91kfJ8DQ:b-gervlj) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/pages/ConceptPages/ShowConceptPage.groovy#L13)):_

> ``` Groovy
>     static at = {
>         title ==~ /Show Concept/
> //        title ==~ /Ver Concept/
> ```

Comentario traduzindo titulo

---

_[test/functional/pages/EvaluationConceptPages/AddEvaluationConceptPage.groovy, line 12 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5XHaZN0n44LBUS9wM:-KW5XHaZN0n44LBUS9wN:b-uta11c) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/pages/EvaluationConceptPages/AddEvaluationConceptPage.groovy#L12)):_

> ``` Groovy
> 
>     static at = {
> //        title ==~ /Criar EvaluationConcept/
> ```

+1 Comentario traduzindo

---

_[test/functional/pages/EvaluationConceptPages/EditEvaluationConceptPage.groovy, line 12 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5XLQ2ulNgxLusrP6I:-KW5XLQ2ulNgxLusrP6J:b-gervlj) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/pages/EvaluationConceptPages/EditEvaluationConceptPage.groovy#L12)):_

> ``` Groovy
> 
>     static at = {
> //        title ==~ /Editar EvaluationConcept/
> ```

Comentario traduzindo titulo

---

_[test/functional/steps/EvalConceptDataAndOperations.groovy, line 14 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5XlFbsha2fXGznqej:-KW5XlFbsha2fXGznqek:b-ns4v25) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/steps/EvalConceptDataAndOperations.groovy#L14)):_

> ``` Groovy
>     public static void createEvalConcept(String nome, List<String> conceitos){
>         def evalConcept = new EvaluationConcept()
>         evalConcept.nome = nome
> ```

podia ser passado no construtor

---

_[test/functional/steps/EvalConceptDataAndOperations.groovy, line 15 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5Xe2G7Ps6iahN52Cy:-KW5Xe2G7Ps6iahN52Cz:be5nguo) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/steps/EvalConceptDataAndOperations.groovy#L15)):_

> ``` Groovy
>         def evalConcept = new EvaluationConcept()
>         evalConcept.nome = nome
>         List l_conceitos = []
> ```

lista nao usada

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/ta/38)_

**Comment by pauloborba** [comment]
Reviewed 15 of 27 files at r1.
Review status: 26 of 27 files reviewed at latest revision, 19 unresolved discussions.

---

_[grails-app/controllers/ta/ConceptController.groovy, line 2 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwe4jvpEeeoGz7oS4A:-KWwe4jvpEeeoGz7oS4B:b20hklo) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/grails-app/controllers/ta/ConceptController.groovy#L2)):_

> ``` Groovy
> package ta
> ```

não entendi porque tem um ConceptController. a principio, bastaria o EvaluationConceptController

---

_[grails-app/domain/ta/EvaluationConcept.groovy, line 11 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwaA0RCa5z3bnpA5WN:-KWwaA0RCa5z3bnpA5WO:b1pqbv8) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/grails-app/domain/ta/EvaluationConcept.groovy#L11)):_

> ``` Groovy
>         conceitos validator: {val, obj ->
>             def retval = true
>             if(!obj?.conceitos?.size()){
> ```

size !=0 é melhor

---

_[test/cucumber/EvalConceptConfiguration.feature, line 20 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWw_JPSbYypz1rF9mWa:-KWw_JPT9ETLiuzQADO7:b-aik21o) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/EvalConceptConfiguration.feature#L20)):_

> ``` Cucumber
>   Scenario: Configure the atual evaluation concept with invalid attributes.
>     Given The evaluation concept is "MA, MPA, MANA"
>     When I update the "MA, MPA, MANA" concept to "New Concept" evaluation concept with no concepts
> ```

não entendi o que isso significa. não tem um caso positivo de criar New Concept? esquisito só contemplar o negativo

---

_[test/cucumber/steps/EvalConceptConfigurationSteps.groovy, line 22 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwalzVWoYoFBGt2r7a:-KWwalzVWoYoFBGt2r7b:b3kre) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/steps/EvalConceptConfigurationSteps.groovy#L22)):_

> ``` Groovy
> 
> Given(~/^The evaluation concept is "([^"]*)"$/) { String nome ->
>     EvaluationConcept.all
> ```

?

---

_[test/cucumber/steps/EvalConceptConfigurationSteps.groovy, line 31 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwbUu8g1cwjXbiJEeL:-KWwbUu8g1cwjXbiJEeM:bwuj4nf) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/steps/EvalConceptConfigurationSteps.groovy#L31)):_

> ``` Groovy
> When(~/^I update the "([^"]*)" concept to "([^"]*)" concept$/) { String inicial, String proximo ->
>     def toUpdate =  EvaluationConcept.findByNome(inicial)
>     assert toUpdate != null
> ```

lógica confusa

---

_[test/cucumber/steps/EvalConceptConfigurationSteps.groovy, line 61 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwd6Ma6nro5RQ1tR4z:-KWwd6Ma6nro5RQ1tR5-:b6vlt5i) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/steps/EvalConceptConfigurationSteps.groovy#L61)):_

> ``` Groovy
> Given(~/^The "([^"]*)" evaluation concept is set$/) { String ini ->
>     String[] conceitos = ini.split(", ")
>     for(conceito in conceitos){
> ```

isso são os valores ou o nome do tipo de conceito que está sendo criado?

---

_[test/cucumber/steps/EvalConceptConfigurationSteps.groovy, line 69 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwdIq4VYNLiq1jVxEb:-KWwdIq4VYNLiq1jVxEc:bvrnpld) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/steps/EvalConceptConfigurationSteps.groovy#L69)):_

> ``` Groovy
>     to AddEvaluationConceptPage
>     at AddEvaluationConceptPage
>     page.fillNameEvalCon(ini)
> ```

usa nomes de métodos mais adequados. a lógica está confusa

---

_[test/cucumber/steps/EvalConceptConfigurationSteps.groovy, line 78 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwdX7-5oPushMmI48o:-KWwdX7-5oPushMmI48p:b-ccbgsm) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/steps/EvalConceptConfigurationSteps.groovy#L78)):_

> ``` Groovy
>     page.editEvalConcept()
>     at EditEvaluationConceptPage
>     page.editEvalConceptWithoutConcept()
> ```

confuso. melhor chamar coisas como MA e MANA de EvaluationConcept, e "Avaliação por Metas" de EvaluationConceptCategory

---

_[test/cucumber/support/env.groovy, line 31 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwa_hyAK790cysWpiL:-KWwa_hyAK790cysWpiM:bk8jm6c) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/support/env.groovy#L31)):_

> ``` Groovy
>     cleanEnvironment()
>     def eConcepts = EvaluationConcept.all
>     for (c in eConcepts){
> ```

não ficaria melhor em cleanEnvironment?

---

_[test/cucumber/support/env.groovy, line 33 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwaVrubL4lukMSqV62:-KWwaVrubL4lukMSqV63:b3kre) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/support/env.groovy#L33)):_

> ``` Groovy
>     for (c in eConcepts){
>         def e = c.delete(flush: true)
>         e
> ```

?

---

_[test/functional/pages/ConceptPages/AddConceptPage.groovy, line 13 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWweLtR8psjAN7bI0TX:-KWweLtR8psjAN7bI0TY:blk4ugs) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/pages/ConceptPages/AddConceptPage.groovy#L13)):_

> ``` Groovy
>     static at = {
> //        title ==~ /Criar Concept/
>         title ==~ /Create Concept/
> ```

internacionalizar

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/ta/38)_

**Comment by jvsn** [comment]
Review status: 13 of 35 files reviewed at latest revision, 19 unresolved discussions.

---

*[grails-app/controllers/ta/ConceptController.groovy, line 2 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwe4jvpEeeoGz7oS4A:-KXn92iRNNxjxCJemvuk:b236r29) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/grails-app/controllers/ta/ConceptController.groovy#L2)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

não entendi porque tem um ConceptController. a principio, bastaria o EvaluationConceptController
</blockquote></details>

Eu tive problemas em criar apenas o EvaluationConceptController pois era complicado escolher quantos conceitos EvaluationConcept teria em tempo real. Além disso eu pensei em dividir em dois controladores para uma futura feature de cálculo de média, onde pode ser adicionado um atributo "Peso" no Concept para futuros cálculos.

---

*[grails-app/domain/ta/EvaluationConcept.groovy, line 5 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5VO7dhlSMRrUDx740:-KXn9pse611Yt0fCcH6-:b-h15clk) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/grails-app/domain/ta/EvaluationConcept.groovy#L5)):*
<details><summary><i>Previously, Arthurlpgc wrote…</i></summary><blockquote>

Ja que o codigo ta todo em ingles, o uso de duas linguas difilcuta o entendimento do codigo
</blockquote></details>

Resolvido.

---

*[grails-app/domain/ta/EvaluationConcept.groovy, line 11 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwaA0RCa5z3bnpA5WN:-KXnA4uVK9Gc8ihQu9BV:b-90ondk) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/grails-app/domain/ta/EvaluationConcept.groovy#L11)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

size !=0 é melhor
</blockquote></details>

Eu tentei modificar mas não tive sucesso.

---

*[test/cucumber/EvalConceptConfiguration.feature, line 20 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWw_JPSbYypz1rF9mWa:-KXnAFZubpuhGgw-LIvw:b7cpj1b) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/EvalConceptConfiguration.feature#L20)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

não entendi o que isso significa. não tem um caso positivo de criar New Concept? esquisito só contemplar o negativo
</blockquote></details>

O caso positivo está implícito em todos os testes pois, como é preciso ter Concepts para formar Evaluation Concept, eu sempre estou criando e testando se tudo está correto.

---

*[test/cucumber/steps/EvalConceptConfigurationSteps.groovy, line 22 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwalzVWoYoFBGt2r7a:-KXnARQ5O8TqYH92vTqt:b-896fix) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/steps/EvalConceptConfigurationSteps.groovy#L22)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

---

*[test/cucumber/steps/EvalConceptConfigurationSteps.groovy, line 31 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwbUu8g1cwjXbiJEeL:-KXnATmavt6pLOpoGDIr:b-ddkx5o) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/steps/EvalConceptConfigurationSteps.groovy#L31)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

lógica confusa
</blockquote></details>

Testo se existe algum EvaluationConcept com o nome "inicial". Caso sim, significa que o conceito foi guardado no banco de dados, sendo ele um erro.

---

*[test/cucumber/steps/EvalConceptConfigurationSteps.groovy, line 61 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwd6Ma6nro5RQ1tR4z:-KXnAVIxB8H9Ex_85cWA:b-896fix) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/steps/EvalConceptConfigurationSteps.groovy#L61)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

isso são os valores ou o nome do tipo de conceito que está sendo criado?
</blockquote></details>

Done.

---

*[test/cucumber/steps/EvalConceptConfigurationSteps.groovy, line 69 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwdIq4VYNLiq1jVxEb:-KXnAWPRGVjY2Hi5jdFs:b-896fix) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/steps/EvalConceptConfigurationSteps.groovy#L69)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

usa nomes de métodos mais adequados. a lógica está confusa
</blockquote></details>

Done.

---

*[test/cucumber/steps/EvalConceptConfigurationSteps.groovy, line 78 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwdX7-5oPushMmI48o:-KXnAXk8wrm7mztzVEX4:bg5pf7u) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/steps/EvalConceptConfigurationSteps.groovy#L78)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

confuso. melhor chamar coisas como MA e MANA de EvaluationConcept, e "Avaliação por Metas" de EvaluationConceptCategory
</blockquote></details>

Eu pensei em mudar mas tomaria muito tempo, renomearia algumas coisas, geraria os controllers e views, etc... Desculpa

---

*[test/cucumber/support/env.groovy, line 31 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwa_hyAK790cysWpiL:-KXnArR1asZ3wyfd8-Dp:b-896fix) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/support/env.groovy#L31)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

não ficaria melhor em cleanEnvironment?
</blockquote></details>

Done.

---

*[test/cucumber/support/env.groovy, line 33 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWwaVrubL4lukMSqV62:-KXnAsNRLzPgLwc5fr2G:b-896fix) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/cucumber/support/env.groovy#L33)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

---

*[test/functional/pages/ConceptPages/AddConceptPage.groovy, line 12 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5WyrRixonZiUECexh:-KXnAtvJI3Kfb5SJemDc:b-896fix) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/pages/ConceptPages/AddConceptPage.groovy#L12)):*
<details><summary><i>Previously, Arthurlpgc wrote…</i></summary><blockquote>

Comentario desnecessario
</blockquote></details>

Done.

---

*[test/functional/pages/ConceptPages/AddConceptPage.groovy, line 13 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KWweLtR8psjAN7bI0TX:-KXnAuPN4ZT7KKw2QvJm:b-896fix) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/pages/ConceptPages/AddConceptPage.groovy#L13)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

internacionalizar
</blockquote></details>

Done.

---

*[test/functional/pages/ConceptPages/EditConceptPage.groovy, line 13 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5X6cx6uZ8_aGZl8Hu:-KXnAv6bhAl6QTnOsCrx:b-896fix) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/pages/ConceptPages/EditConceptPage.groovy#L13)):*
<details><summary><i>Previously, Arthurlpgc wrote…</i></summary><blockquote>

De novo, comentario de tradução de titulo
</blockquote></details>

Done.

---

*[test/functional/pages/ConceptPages/ShowConceptPage.groovy, line 13 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5XBFYYx9C91kfJ8DP:-KXnAvlCPCbI_T4-XnAK:b-896fix) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/pages/ConceptPages/ShowConceptPage.groovy#L13)):*
<details><summary><i>Previously, Arthurlpgc wrote…</i></summary><blockquote>

Comentario traduzindo titulo
</blockquote></details>

Done.

---

*[test/functional/pages/EvaluationConceptPages/AddEvaluationConceptPage.groovy, line 12 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5XHaZN0n44LBUS9wM:-KXnAyV7QXuFNtc5zPnY:b-896fix) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/pages/EvaluationConceptPages/AddEvaluationConceptPage.groovy#L12)):*
<details><summary><i>Previously, Arthurlpgc wrote…</i></summary><blockquote>

+1 Comentario traduzindo
</blockquote></details>

Done.

---

*[test/functional/pages/EvaluationConceptPages/EditEvaluationConceptPage.groovy, line 12 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5XLQ2ulNgxLusrP6I:-KXnAzjZaUHNT14F3UIW:b-896fix) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/pages/EvaluationConceptPages/EditEvaluationConceptPage.groovy#L12)):*
<details><summary><i>Previously, Arthurlpgc wrote…</i></summary><blockquote>

Comentario traduzindo titulo
</blockquote></details>

Done.

---

*[test/functional/steps/EvalConceptDataAndOperations.groovy, line 14 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5XlFbsha2fXGznqej:-KXnB08cOo6cA2a52E1V:b-896fix) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/steps/EvalConceptDataAndOperations.groovy#L14)):*
<details><summary><i>Previously, Arthurlpgc wrote…</i></summary><blockquote>

podia ser passado no construtor
</blockquote></details>

Done.

---

*[test/functional/steps/EvalConceptDataAndOperations.groovy, line 15 at r1](https://reviewable.io:443/reviews/pauloborba/ta/38#-KW5Xe2G7Ps6iahN52Cy:-KXnB0rk2aIIe0CgEVDE:b-896fix) ([raw file](https://github.com/pauloborba/ta/blob/8f3a6135e84e59c588a8a13e1733c618d7b01fc3/test/functional/steps/EvalConceptDataAndOperations.groovy#L15)):*
<details><summary><i>Previously, Arthurlpgc wrote…</i></summary><blockquote>

lista nao usada
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/ta/38)*

**Comment by jvsn** [comment]
Professor, acabei modificando alguns arquivos antigos e isso gerou erros no fim. Os arquivos antigos não estão internacionalizados. Peço desculpas pelo transtorno.

**Comment by pauloborba** [comment]
Reviewed 1 of 22 files at r2.
Review status: 14 of 35 files reviewed at latest revision, 16 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/ta/38)*

**Comment by Arthurlpgc** [comment]
Reviewed 21 of 22 files at r2.
Review status: 34 of 35 files reviewed at latest revision, 10 unresolved discussions.

---

*[grails-app/domain/ta/Evaluation.groovy, line 4 at r2](https://reviewable.io:443/reviews/pauloborba/ta/38#-KYBYPdHtd6FbTKyUC0w:-KYBYPdHtd6FbTKyUC0x:b-f3th33) ([raw file](https://github.com/pauloborba/ta/blob/f8830147275ddb1fd6b6e8b0fbfae925bb70c8c1/grails-app/domain/ta/Evaluation.groovy#L4)):*
> ```Groovy
> 
> class Evaluation {
>     static private List<String> defaultConcepts = ["MA","MPA","MANA","--"];
> ```

Usou strings para representar Concepts, ao inves da classe criada por ele para isso.

---

*[grails-app/views/evaluation/_editForm.gsp, line 41 at r2](https://reviewable.io:443/reviews/pauloborba/ta/38#-KYBZNSsOVfz5DHSKDPu:-KYBZ55Xgqaw42hJ0RNj:b-8gge3z) ([raw file](https://github.com/pauloborba/ta/blob/f8830147275ddb1fd6b6e8b0fbfae925bb70c8c1/grails-app/views/evaluation/_editForm.gsp#L41)):*
> ```gsp
>     </g:if>
>     <g:else>
>         <g:select name="value" from="${["MA", "MPA", "MANA", "--"]}" required="" value="${evaluationInstance?.value}" valueMessagePrefix="evaluation.value"/>
> ```

Codigo agora tem duas classes que fazem a mesma coisa, so que uma mais capaz que a outra sem herdar..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/ta/38)*

**Pull request closed without merging**
