### PR TITLE
Consertando alguns detalhes no TA

### PR DESCRIPTION
**Pull request by milenascc**
This change is [Reviewable](https://reviewable.io/reviews/pauloborba/ta/31)

### CODE REVIEW

**Comment by pauloborba** [comment]
Reviewed 2 of 11 files at r2, 3 of 76 files at r5, 3 of 3 files at r6.
Review status: 7 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

_[.idea/modules.xml, line 1 at r6](https://reviewable.io:443/reviews/pauloborba/ta/31#-KSEHmidNXKi3yj3_sMD:-KSEHmidNXKi3yj3_sME:b-r961uv) ([raw file](https://github.com/pauloborba/ta/blob/80b53b292ea23dd67a9701d86429849096d84e83/.idea/modules.xml#L1)):_

> ``` XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

esse arquivo não deve ir para o repositório principal, certo?

---

_[grails-app/controllers/ta/StudentController.groovy, line 143 at r6](https://reviewable.io:443/reviews/pauloborba/ta/31#-KSEI8GhcBmFDp8DflLg:-KSEI8GhcBmFDp8DflLh:bayf8m) ([raw file](https://github.com/pauloborba/ta/blob/bc6e96fb7f4648c9a5aaf090af9dfa12aa3c0d31/grails-app/controllers/ta/StudentController.groovy#L143)):_

> ``` Groovy
>     }
> 
>     public double checkPorcentageEvaluationStudent(String evalValue, String loginA) {
> ```

esse método não era usado?

---

_[test/integration/ReportSteps.groovy, line 0 at r6](https://reviewable.io:443/reviews/pauloborba/ta/31#-KSEIIpEvjJVyIHsDcjh:-KSEIIpEvjJVyIHsDcji:b-ke1y9b) ([raw file](https://github.com/pauloborba/ta/blob/80b53b292ea23dd67a9701d86429849096d84e83/test/integration/ReportSteps.groovy#L0)):_
esse arquivo não era usado?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/ta/31)_

**Comment by milenascc** [comment]
Quanto ao xml eu não tenho certeza
O método havia deixado de ser usado, na hora de juntar com a versão de Calegario acabou que haviam dois métodos similares e só um deles era usado, por isso apaguei.
Quanto ao arquivo, era meu antigo arquivo de steps que em certo momento não conseguiu mais linkar com os cenários do .feature, então ele ficou inutilizado depois de eu fazer outro arquivo pros steps.

**Comment by pauloborba** [comment]
Review status: 7 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

_[.idea/modules.xml, line 1 at r6](https://reviewable.io:443/reviews/pauloborba/ta/31#-KSEHmidNXKi3yj3_sMD:-KSHHqNwNoEZIXW1Y1cl:b397qr) ([raw file](https://github.com/pauloborba/ta/blob/80b53b292ea23dd67a9701d86429849096d84e83/.idea/modules.xml#L1)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> esse arquivo não deve ir para o repositório principal, certo?
> </details>
> tudo que é do .idea não deve ser subido para o repositório. remove e ajusta o pull, por favor

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/ta/31)_

**Comment by milenascc** [comment]
Review status: 6 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

_[.idea/modules.xml, line 1 at r6](https://reviewable.io:443/reviews/pauloborba/ta/31#-KSEHmidNXKi3yj3_sMD:-KSHPMbeFgKT1g-UipSi:b-vpma4x) ([raw file](https://github.com/pauloborba/ta/blob/80b53b292ea23dd67a9701d86429849096d84e83/.idea/modules.xml#L1)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> tudo que é do .idea não deve ser subido para o repositório. remove e ajusta o pull, por favor
> </details>
> Acabei de dar push para meu fork, e pelo que vi, ele excluiu o .xml, agora está ok?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/ta/31)_

**Comment by milenascc** [comment]
Review status: 6 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

_[test/integration/ReportSteps.groovy, line  at r6](https://reviewable.io:443/reviews/pauloborba/ta/31#-KSEIIpEvjJVyIHsDcjh:-KSHQ9Ht8DHIsllYgubf:bxqkkce) ([raw file](https://github.com/pauloborba/ta/blob/80b53b292ea23dd67a9701d86429849096d84e83/test/integration/ReportSteps.groovy#L)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> esse arquivo não era usado?
> </details>
> Ele era usado, depois parou de linkar com os cenários, então fiz outro arquivo e deixei de usar esse

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/ta/31)_

**Comment by milenascc** [comment]
Review status: 6 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

_[grails-app/controllers/ta/StudentController.groovy, line 143 at r6](https://reviewable.io:443/reviews/pauloborba/ta/31#-KSEI8GhcBmFDp8DflLg:-KSHQJcGmAXfR0YJ_23s:b-g9q2eg) ([raw file](https://github.com/pauloborba/ta/blob/bc6e96fb7f4648c9a5aaf090af9dfa12aa3c0d31/grails-app/controllers/ta/StudentController.groovy#L143)):_
<details><summary>

<i>Previously, pauloborba (Paulo Borba) wrote…</i></summary>



> esse método não era usado?
> </details>
> Na minha versão, esse método não era mais utilizado mas acabou ficando no código até agora

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/ta/31)_

**Comment by pauloborba** [comment]
Reviewed 1 of 11 files at r2, 2 of 76 files at r5, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/ta/31)_

**Pull request merged**
